#!/usr/bin/env python3
"""Coverage: which of a benchmark's languages each entry *can* name, and how
right it is on those → <bench>/COVERAGE.md.

    python3 tools/coverage.py benchmarks/bench-linguist --synid path/to/synid

A tool that cannot output a language cannot be right on it, however good it
is: its accuracy mixes skill with the size of its label set. This report
separates the two — *coverage* (cases whose expected language is among the
tool's labels) and *accuracy on covered cases*.

Label sets: Synid's from `synid info syntaxes` (the binary given, run locally;
its list is not stored here); the other tools' from
tools/external/<tool>/labels.json (`tools/external.py --tool X --labels`),
mapped through names.csv; Jev with Linguist's languages chooses among all of
them; a local LLM answers freely (open vocabulary). A label matches a case
when it is the expected language or one of its accepted names, or a Linguist
alias of one (case, spaces and punctuation ignored).
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))
from external import name_map  # noqa: E402
from leaderboard import entry_name, load_runs  # noqa: E402
from score import LINGUIST_NAMES, metrics, name_key, pct, read_cases  # noqa: E402

OPEN = "open vocabulary"


def label_set(meta: dict, synid: str | None) -> set[str] | str | None:
    kind, label = meta.get("kind", "synid"), meta.get("label", "")
    if kind == "synid":
        if not synid:
            return None
        out = subprocess.run([synid, "info", "syntaxes"], capture_output=True, text=True).stdout
        return {name_key(x) for x in out.splitlines() if x.strip()}
    if label.startswith(("jev-linguist", "kev-linguist")):
        langs = json.loads((HERE / "data" / "linguist_languages.json").read_text(encoding="utf-8"))["languages"]
        return {name_key(n) for lang in langs for n in [lang["name"], *lang["aliases"]]}
    if label.startswith("jev-study63"):  # the languages that have a label of their own
        st = json.loads((HERE / "data" / "jev_study_labels.json").read_text(encoding="utf-8"))
        return {name_key(v[0]) for v in st["to_linguist"].values() if len(v) == 1}
    if label.startswith("jev-cascade"):  # candidates, or the fallback list: every language of the snapshot
        d = json.loads((HERE / "data" / "pl_candidates.json").read_text(encoding="utf-8"))
        return {name_key(lg["name"]) for lg in d["languages"].values()} | {name_key("Text")}
    if label.startswith("llm-"):
        return OPEN
    tool = label.removeprefix("ext-").removesuffix("-content-only")
    p = HERE / "external" / tool / "labels.json"
    if not p.exists():
        return None
    mapping = name_map(tool)
    return {name_key(n) for lab in json.loads(p.read_text(encoding="utf-8")) for n in mapping.get(lab, [lab])}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("bench", type=Path)
    ap.add_argument("--synid", help="a synid binary, to list its syntaxes (the latest version is assumed)")
    a = ap.parse_args()
    bench = a.bench.resolve()
    cases = read_cases(bench)
    ids = list(cases)
    langs = {c["expected"] for c in cases.values()}
    rows = []
    for meta, ans, _ in load_runs(bench):
        if meta.get("kind") in ("ground-truth", "llm-judge"):
            continue
        ls = label_set(meta, a.synid)
        if ls is None:
            continue
        if ls == OPEN:
            covered = ids
        else:
            covered = [i for i in ids if any(k in ls for x in cases[i]["accept"].split(";") if x
                                             for k in LINGUIST_NAMES.get(name_key(x), {name_key(x)}))]
        n_lang = len({cases[i]["expected"] for i in covered})
        m_all, m_cov = metrics(cases, ans, ids), metrics(cases, ans, covered)
        rows.append((entry_name(meta), "open" if ls == OPEN else len(ls), n_lang, len(covered), m_all, m_cov))
    rows.sort(key=lambda r: -(r[4]["accuracy"] or 0))
    out = [f"# Coverage — {bench.name}", "",
           f"Generated by `python3 tools/coverage.py benchmarks/{bench.name}`. A tool cannot be right on a language "
           "it cannot name: *coverage* counts the cases whose expected language is among the tool's labels, "
           "*accuracy on covered cases* how right it is there. Synid's label set is read from the latest Synid "
           "binary (`synid info syntaxes`); the other tools' from `tools/external/<tool>/labels.json`.", "",
           f"{len(cases)} cases in {len(langs)} languages.", "",
           "| entry | labels it can output | benchmark languages it can name | covered cases | accuracy, all cases "
           "| accuracy on covered cases |", "|---|---:|---:|---:|---:|---:|"]
    for name, nl, n_lang, n_cov, m_all, m_cov in rows:
        out.append(f"| {name} | {nl} | {n_lang}/{len(langs)} | {n_cov}/{len(cases)} ({pct(n_cov / len(cases))}) | "
                   f"{m_all['right']}/{m_all['n']} ({pct(m_all['accuracy'])}) | "
                   f"{m_cov['right']}/{m_cov['n']} ({pct(m_cov['accuracy'])}) |")
    (bench / "COVERAGE.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"{bench.name}: {len(rows)} entries → {bench / 'COVERAGE.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
