#!/usr/bin/env python3
"""Failure report: every case a Synid run gets wrong, with the program and the
root cause → <bench>/FAILURES.md.

    python3 tools/failures.py benchmarks/bench-m                 # latest baseline vs the previous one
    python3 tools/failures.py benchmarks/bench-m --run 48c3c45-default --previous 9bc1c32-default

Root causes come from the benchmark's own `root_causes.py` (CAUSES: title,
mechanism, evidence, how it was verified, suggested fix; diagnose(case, text,
answers) → cause id). Without one, failures are grouped by outcome and tags.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from score import outcome, read_cases, read_run  # noqa: E402

EXCERPT_LINES = 14
SWH = "https://archive.softwareheritage.org"


def load_causes(bench: Path):
    p = bench / "root_causes.py"
    if not p.exists():
        return {}, None
    spec = importlib.util.spec_from_file_location("root_causes", p)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.CAUSES, mod.diagnose


def runs_by_label(bench: Path) -> dict[str, tuple[dict, dict]]:
    out = {}
    for sub in ("baselines", "entries"):
        for p in sorted((bench / sub).glob("*.jsonl")) if (bench / sub).is_dir() else []:
            meta, ans = read_run(p)
            out[p.stem] = (meta, ans)
    return out


def latest_two_baselines(bench: Path) -> tuple[str, str | None]:
    bs = []
    for p in (bench / "baselines").glob("*.jsonl"):
        meta = json.loads(p.read_text(encoding="utf-8").splitlines()[0])["meta"]
        bs.append((meta.get("date", ""), p.stem))
    bs.sort()
    return bs[-1][1], (bs[-2][1] if len(bs) > 1 else None)


def excerpt(raw: bytes) -> tuple[str, str]:
    try:
        text, note = raw.decode("utf-8"), ""
    except UnicodeDecodeError:
        text, note = raw.decode("latin-1"), " (not valid UTF-8 — shown as Latin-1)"
    lines = [ln.rstrip()[:110] for ln in text.splitlines()]
    while lines and not lines[0].strip():
        lines.pop(0)
    shown = lines[:EXCERPT_LINES]
    more = len(lines) - len(shown)
    body = "\n".join(shown).replace("```", "``​`")
    return body + (f"\n… ({more} more lines)" if more > 0 else ""), note


def fmt(ans) -> str:
    if not ans:
        return "no answer"
    return ans[0] if len(ans) == 1 else f"undecided ({len(ans)} candidates)"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("bench", type=Path)
    ap.add_argument("--run", help="run label (default: latest baseline)")
    ap.add_argument("--previous", help="earlier run to compare with (default: the baseline before it)")
    a = ap.parse_args()
    bench = a.bench.resolve()
    cases = read_cases(bench)
    runs = runs_by_label(bench)
    latest, prev = latest_two_baselines(bench)
    run_l, prev_l = a.run or latest, a.previous or (prev if not a.run else None)
    meta, ans = runs[run_l]
    causes, diagnose = load_causes(bench)
    answers_all = {lab: r[1] for lab, r in runs.items()}

    def case_answers(cid):
        return {lab: a_.get(cid) for lab, a_ in answers_all.items()}

    def text_of(c):
        return (bench / "files" / c["sha1_git"]).read_bytes().decode("utf-8", "replace")

    failing = [cid for cid, c in cases.items() if outcome(c, ans.get(cid)) != "right"]
    groups = defaultdict(list)
    for cid in failing:
        c = cases[cid]
        cause = diagnose(c, text_of(c), case_answers(cid)) if diagnose else None
        groups[cause or f"{outcome(c, ans.get(cid))}: {c['tags'] or 'no tag'}"].append(cid)
    fixed = []
    if prev_l and prev_l in runs:
        pans = runs[prev_l][1]
        fixed = [cid for cid, c in cases.items()
                 if outcome(c, pans.get(cid)) != "right" and outcome(c, ans.get(cid)) == "right"]

    title = f"Synid {meta.get('commit', '?')}" + (f" ({meta['date']})" if meta.get("date") else "")
    out = [f"# Failure report — {bench.name}, {title}", "",
           f"Generated by `python3 tools/failures.py benchmarks/{bench.name}`. Every case "
           f"`{run_l}` gets wrong ({len(failing)} of {len(cases)}), grouped by root cause, with the program, "
           f"Synid's answer, the expected language (blind human review) and the evidence"
           + (f"; then the cases fixed since `{prev_l}`." if prev_l else ".")
           + " Root causes are documented in `root_causes.py`.", "",
           "| root cause | files | suggested fix | verified by |", "|---|---:|---|---|"]
    order = sorted(groups, key=lambda g: -len(groups[g]))
    for g in order:
        cz = causes.get(g, {})
        out.append(f"| [{cz.get('title', g)}](#{g}) | {len(groups[g])} | {cz.get('fix', '—')} | "
                   f"{cz.get('verified', '—')} |")
    if fixed:
        out.append(f"| *fixed since `{prev_l}`* | {len(fixed)} | | |")

    ablations = [lab for lab, (m, _) in runs.items() if m.get("kind", "synid") == "synid" and m.get("disabled")
                 and m.get("commit") == meta.get("commit")]

    def case_block(cid, show_prev=False):
        c = cases[cid]
        raw = (bench / "files" / c["sha1_git"]).read_bytes()
        body, note = excerpt(raw)
        a_ = case_answers(cid)
        ev = [f"Synid `{run_l}`: **{fmt(a_[run_l])}**"]
        if show_prev:
            ev.append(f"before (`{prev_l}`): {fmt(a_[prev_l])}")
        for lab in ablations:
            d = ", ".join(runs[lab][0].get("disabled") or [])
            ev.append(f"without {d}: {fmt(a_[lab])}")
        if "linguist" in a_:
            ev.append(f"Linguist `.m` rules: {fmt(a_['linguist'])}")
        return [f"#### `{c['filename']}`", "",
                f"expected **{c['expected_detail']}** · [archived file]({SWH}/{c['qualified_swhid']}/) · "
                f"[in this benchmark](files/{c['sha1_git']}) · {len(raw):,} bytes"
                + (f" · tags: {c['tags']}" if c["tags"] else ""), "",
                " · ".join(ev), "", f"```{note}", body, "```", ""]

    for g in order:
        cz = causes.get(g, {})
        out += ["", f'<a id="{g}"></a>', f"## {cz.get('title', g)} — {len(groups[g])} file(s)", ""]
        if cz:
            out += [f"**Mechanism.** {cz['mechanism']}", "", f"**Evidence.** {cz['evidence']}.", "",
                    f"**Verified.** {cz['verified']}.", "", f"**Suggested fix.** {cz['fix']}.", ""]
        for cid in sorted(groups[g], key=lambda i: cases[i]["filename"].lower()):
            out += case_block(cid)
    if fixed:
        out += ["", f"## Fixed since `{prev_l}` — {len(fixed)} file(s)", ""]
        for cid in fixed:
            c = cases[cid]
            pg = diagnose(c, text_of(c), case_answers(cid)) if diagnose else None
            if pg and pg in causes:
                out += [f"**{causes[pg]['title']}.** {causes[pg]['mechanism']} *{causes[pg]['verified']}.*", ""]
            out += case_block(cid, show_prev=True)
    (bench / "FAILURES.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"{bench.name}: {len(failing)} failures of {run_l} in {len(groups)} group(s), {len(fixed)} fixed since "
          f"{prev_l} → {(bench / 'FAILURES.md')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
