#!/usr/bin/env python3
"""Summarise every stored baseline of a benchmark into its HISTORY.md — the record
of Synid versions on it (accuracy, and per failure trigger).

    python3 tools/history.py benchmarks/bench-m
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from score import metrics, pct, read_cases, read_run  # noqa: E402


def main() -> int:
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    bench = Path(sys.argv[1]).resolve()
    out_path = bench / "HISTORY.md"
    cases = read_cases(bench)
    tiers, tags = defaultdict(list), defaultdict(list)
    for cid, c in cases.items():
        tiers[c["tier"]].append(cid)
        for t in filter(None, c["tags"].split(";")):
            tags[t].append(cid)
    runs = []
    for p in sorted((bench / "baselines").glob("*.jsonl")):
        meta, ans = read_run(p)
        runs.append((meta, ans))
    runs.sort(key=lambda r: r[0].get("date", "") or r[0].get("label", ""))
    tag_names = sorted(tags, key=lambda t: -len(tags[t]))
    lines = [f"# Synid on {bench.name} — history", "",
             f"Generated by `python3 tools/history.py benchmarks/{bench.name}` from `baselines/*.jsonl` "
             f"({len(cases)} cases). "
             "Accuracy = exactly one syntax, and an accepted one (README.md).", "",
             "| run | Synid commit | right | accuracy, weighted to the population (if the benchmark has weights) | " + " | ".join(tag_names) + " |",
             "|---|---|---:|---:|" + "---:|" * len(tag_names)]
    for meta, ans in runs:
        g = metrics(cases, ans, list(cases), weighted=True)
        cells = [f"{metrics(cases, ans, tags[t])['right']}/{len(tags[t])}" for t in tag_names]
        lines.append(f"| `{meta.get('label')}` | `{meta.get('commit') or '?'}` | {g['right']}/{g['n']} "
                     f"({pct(g['accuracy'])}) | {pct(g.get('weighted', {}).get('accuracy'))} | "
                     + " | ".join(cells) + " |")
    lines += ["", "Tag columns: right / cases carrying that failure trigger "
                  f"({', '.join(f'{t} {len(tags[t])}' for t in tag_names)}).", ""]
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(runs)} baseline(s) → {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
