#!/usr/bin/env python3
"""Leaderboards: one per benchmark (benchmarks/<name>/LEADERBOARD.md) and an
overall one (LEADERBOARD.md), from every recorded run — Synid versions
(baselines/) and other entries (entries/: Synid configurations, other
identifiers, LLM judges).

    python3 tools/leaderboard.py

Ranking: accuracy (exactly one syntax, and an accepted one), then precision of
language answers. LLM judges that were used to cross-check a benchmark's ground
truth are listed apart, not ranked. Overall: an entry is the same system and
configuration across benchmarks; micro = all cases pooled, macro = mean of the
benchmarks' accuracies; only benchmarks the entry was run on count.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))
from score import metrics, pct, read_cases, read_run  # noqa: E402

DEFAULT_STRATEGIES_NOTE = "default"


def entry_name(meta: dict) -> str:
    if meta.get("name"):
        return meta["name"]
    commit = meta.get("commit") or "?"
    dis = meta.get("disabled") or []
    return f"Synid {commit}" + (f" without {', '.join(dis)}" if dis else "")


def load_runs(bench: Path) -> list[tuple[dict, dict, str]]:
    runs = []
    for sub in ("baselines", "entries"):
        for p in sorted((bench / sub).glob("*.jsonl")) if (bench / sub).is_dir() else []:
            meta, ans = read_run(p)
            runs.append((meta, ans, sub))
    return runs


def bench_board(bench: Path) -> tuple[str, dict[str, dict]]:
    cases = read_cases(bench)
    ids = list(cases)
    tags: dict[str, list[str]] = {}
    for cid, c in cases.items():
        for t in filter(None, c.get("tags", "").split(";")):
            tags.setdefault(t, []).append(cid)
    tag_names = sorted(tags, key=lambda t: -len(tags[t]))
    has_weights = any(c.get("weight") for c in cases.values())
    version = (bench / "cases.csv").read_text(encoding="utf-8").splitlines()[0].lstrip("# ").split(" —")[0]
    rows, judges, by_name = [], [], {}
    for meta, ans, sub in load_runs(bench):
        m = metrics(cases, ans, ids, weighted=has_weights)
        name = entry_name(meta)
        rec = {"name": name, "meta": meta, "m": m, "baseline": sub == "baselines",
               "tags": {t: metrics(cases, ans, tags[t])["right"] for t in tag_names}}
        (judges if meta.get("kind") == "llm-judge" else rows).append(rec)
        by_name[name] = {"right": m["right"], "n": m["n"], "accuracy": m["accuracy"],
                         "kind": meta.get("kind", "synid")}
    rows.sort(key=lambda r: (-(r["m"]["accuracy"] or 0), -(r["m"]["precision"] or 0), r["name"]))

    def line(rank, r):
        m, o = r["m"], r["m"]["outcomes"]
        kind = {"synid": "Synid", "other-identifier": "other identifier", "llm-judge": "LLM judge"}.get(
            r["meta"].get("kind", "synid"), r["meta"].get("kind", ""))
        w = f" | {pct(m['weighted']['accuracy'])}" if has_weights else ""
        return (f"| {rank} | {r['name']}{' (baseline)' if r['baseline'] else ''} | {kind} | "
                f"**{m['right']}/{m['n']}** ({pct(m['accuracy'])}) [{pct(m['ci'][0])}, {pct(m['ci'][1])}]{w} | "
                f"{pct(m['precision'])} | {o.get('text', 0)} | {o.get('undecided', 0) + o.get('none', 0)} | "
                f"{o.get('wrong', 0)} | " + " | ".join(f"{r['tags'][t]}/{len(tags[t])}" for t in tag_names) + " |")

    head = ("| # | entry | kind | right (accuracy) [95 % CI]" + (" | weighted to the population" if has_weights else "")
            + " | precision of language answers | `Text` on code | no answer / undecided | wrong language | "
            + " | ".join(f"`{t}`" for t in tag_names) + " |")
    sep = "|---:|---|---|---:|" + ("---:|" if has_weights else "") + "---:|---:|---:|---:|" + "---:|" * len(tag_names)
    out = [f"# Leaderboard — {bench.name}", "",
           f"Generated by `python3 tools/leaderboard.py` · benchmark `{version}`, {len(ids)} cases "
           f"([README](README.md), [history of Synid versions](HISTORY.md)). A case is right when the entry gives "
           "exactly one language and it is accepted; ranked by accuracy, then precision of language answers. "
           "Trigger columns: right / cases with that failure trigger.", "", head, sep]
    out += [line(i, r) for i, r in enumerate(rows, 1)]
    if judges:
        out += ["", "**Reference, not ranked** — LLM judges whose agreement with the human labels is part of "
                    "the evidence for this benchmark's ground truth, so they are not independent of it:", "",
                head, sep]
        out += [line("–", r) for r in judges]
    notes = [f"- **{r['name']}** — {r['meta']['note']}" for r in rows + judges if r["meta"].get("note")]
    if notes:
        out += ["", "Notes:", ""] + notes
    return "\n".join(out) + "\n", by_name


def main() -> int:
    benches = sorted(p for p in (ROOT / "benchmarks").iterdir() if (p / "cases.csv").exists())
    per_bench: dict[str, dict[str, dict]] = {}
    for b in benches:
        text, by_name = bench_board(b)
        (b / "LEADERBOARD.md").write_text(text, encoding="utf-8")
        per_bench[b.name] = by_name
        print(f"{b.name}: {len(by_name)} entries → {(b / 'LEADERBOARD.md').relative_to(ROOT)}")
    names = sorted({n for d in per_bench.values() for n in d})
    rows = []
    for n in names:
        got = {b: d[n] for b, d in per_bench.items() if n in d}
        right, total = sum(g["right"] for g in got.values()), sum(g["n"] for g in got.values())
        macro = sum(g["accuracy"] for g in got.values()) / len(got)
        kind = next(iter(got.values()))["kind"]
        rows.append((n, kind, got, right, total, macro))
    ranked = sorted((r for r in rows if r[1] != "llm-judge"), key=lambda r: (-r[3] / r[4], -r[5], r[0]))
    judges = [r for r in rows if r[1] == "llm-judge"]
    bnames = [b.name for b in benches]
    head = ("| # | entry | benchmarks | right, all cases (micro) | mean accuracy (macro) | "
            + " | ".join(f"[{b}](benchmarks/{b}/LEADERBOARD.md)" for b in bnames) + " |")
    sep = "|---:|---|---:|---:|---:|" + "---:|" * len(bnames)

    def line(rank, r):
        n, kind, got, right, total, macro = r
        cells = [f"{got[b]['right']}/{got[b]['n']}" if b in got else "—" for b in bnames]
        return (f"| {rank} | {n} | {len(got)}/{len(bnames)} | **{right}/{total}** ({pct(right / total)}) | "
                f"{pct(macro)} | " + " | ".join(cells) + " |")

    out = ["# Leaderboard — all benchmarks", "",
           "Generated by `python3 tools/leaderboard.py`. Per-benchmark leaderboards (with failure triggers, "
           "intervals and population weights) are linked in the header. An entry is one system and configuration; "
           "micro pools all cases of the benchmarks it was run on, macro averages their accuracies.", "",
           head, sep] + [line(i, r) for i, r in enumerate(ranked, 1)]
    if judges:
        out += ["", "Reference, not ranked (LLM judges whose agreement backs the ground truth):", "", head, sep]
        out += [line("–", r) for r in judges]
    (ROOT / "LEADERBOARD.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"overall: {len(ranked)} ranked entries → LEADERBOARD.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
