#!/usr/bin/env python3
"""Run a Synid binary over a benchmark's cases → <benchmark>/results/<label>.jsonl.

    python3 tools/run.py benchmarks/bench-m --synid path/to/synid --label head-default
    python3 tools/run.py benchmarks/bench-m --synid path/to/synid --label head-nocomment --disable comment

Works across Synid versions: the configuration is generated by the binary
itself (`synid info generate-config`), then the networked strategy
(linguist-api, which asks GitHub/GitLab about the repository) is removed —
the benchmark measures what Synid infers from a file's name and bytes — plus
any strategy given with --disable. Each file is run under its archived file
name, since Synid's first strategies look at the name.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

OFFLINE_EXCLUDE = {"linguistapi", "linguist-api", "linguist_api"}


def read_cases(bench: Path) -> list[dict]:
    with (bench / "cases.csv").open(encoding="utf-8") as f:
        return list(csv.DictReader(line for line in f if not line.startswith("#")))


def materialise(bench: Path, cases: list[dict], work: Path) -> dict[str, str]:
    """Write each case's bytes (files/<sha1_git>) to work/<sha>/<filename>; returns sha → filename."""
    data = {c["sha1_git"]: (bench / "files" / c["sha1_git"]).read_bytes() for c in cases}
    names = {}
    for c in cases:
        name = re.sub(r"[^\w.+-]", "_", c["filename"] or "file")[:120] or "file"
        if not name.endswith(c["ext"]):
            name += c["ext"]
        (work / c["sha1_git"]).mkdir(parents=True, exist_ok=True)
        (work / c["sha1_git"] / name).write_bytes(data[c["sha1_git"]])
        names[c["sha1_git"]] = name
    return names


def make_config(synid: str, cfg: Path, out_dir: Path, disable: set[str]) -> list[str]:
    """Generated default config, minus the networked strategy and `disable`. Returns enabled strategies."""
    subprocess.run([synid, "info", "generate-config", str(cfg)], check=True, capture_output=True)
    text = cfg.read_text(encoding="utf-8")
    m = re.search(r"(?ms)^enable\s*=\s*\[(.*?)\]", text)
    if not m:
        raise SystemExit("cannot find the [strategies] enable list in the generated config")
    names = re.findall(r'"([^"]+)"', m.group(1))
    norm = lambda s: s.replace("-", "").replace("_", "").lower()  # noqa: E731
    drop = {norm(s) for s in OFFLINE_EXCLUDE | disable}
    keep = [s for s in names if norm(s) not in drop]
    text = text[: m.start(1)] + ", ".join(json.dumps(s) for s in keep) + text[m.end(1):]
    text = re.sub(r'(?m)^(\s*directory\s*=\s*).*$', lambda mm: f'{mm.group(1)}"{out_dir}"', text)
    cfg.write_text(text, encoding="utf-8")
    return keep


def parse_output(stdout: str, work: Path) -> dict[str, list[str]]:
    """`synid file` output → sha → answer. Accepts the text format (a path line, then
    a JSON list) and JSON lines carrying a path and a list of syntaxes."""
    res, cur = {}, None
    for line in stdout.splitlines():
        s = line.strip()
        if not s:
            continue
        if s.startswith("{"):
            try:
                d = json.loads(s)
            except json.JSONDecodeError:
                continue
            path = next((d[k] for k in ("path", "file", "name") if isinstance(d.get(k), str)), None)
            syn = next((d[k] for k in ("syntaxes", "syntax", "languages", "result") if k in d), None)
            if path and syn is not None:
                res[Path(path).parent.name] = syn if isinstance(syn, list) else [syn]
            continue
        if s.startswith("["):
            if cur:
                res[cur] = json.loads(s)
                cur = None
            continue
        if str(work) in s or s.startswith("/"):
            cur = Path(s).parent.name
    return res


def synid_version(synid: str) -> dict:
    v = subprocess.run([synid, "--version"], capture_output=True, text=True).stdout.strip()
    commit = ""
    for d in [Path(synid).resolve(), *Path(synid).resolve().parents]:
        if (d / ".git").exists():
            commit = subprocess.run(["git", "-C", str(d), "rev-parse", "--short", "HEAD"],
                                    capture_output=True, text=True).stdout.strip()
            date, subject = (subprocess.run(["git", "-C", str(d), "log", "-1", "--format=%cs%x09%s"],
                                            capture_output=True, text=True).stdout.strip().split("\t") + [""])[:2]
            return {"version": v, "commit": commit, "date": date, "commit_subject": subject}
    return {"version": v, "commit": commit}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("bench", type=Path, help="benchmark directory, e.g. benchmarks/bench-m")
    ap.add_argument("--synid", required=True, help="path to the synid binary")
    ap.add_argument("--label", required=True, help="name of this run (results/<label>.jsonl)")
    ap.add_argument("--disable", action="append", default=[], help="strategy to disable (repeatable)")
    a = ap.parse_args()
    bench = a.bench.resolve()
    cases = read_cases(bench)
    results = bench / "results"
    results.mkdir(exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="synid-bench-") as tmp:
        tmp = Path(tmp)
        work, out_dir = tmp / "files", tmp / "out"
        work.mkdir()
        out_dir.mkdir()
        materialise(bench, cases, work)
        strategies = make_config(a.synid, tmp / "config.toml", out_dir, set(a.disable))
        p = subprocess.run([a.synid, "file", "--config", str(tmp / "config.toml"), str(work)],
                           capture_output=True, text=True)
        if p.returncode != 0:
            raise SystemExit(f"synid failed ({p.returncode}): {p.stderr[-2000:]}")
        answers = parse_output(p.stdout, work)
        if not answers:
            (results / f"{a.label}.stdout.txt").write_text(p.stdout[:200000], encoding="utf-8")
            raise SystemExit(f"could not parse synid output — saved to results/{a.label}.stdout.txt")
    meta = {"label": a.label, "kind": "synid", **synid_version(a.synid), "strategies": strategies,
            "disabled": sorted(a.disable),
            "config": ("default strategies" if not a.disable else
                       "[strategies] disable = [" + ", ".join(f'"{x}"' for x in sorted(a.disable)) + "]")
                      + " (networked linguist-api off)",
            "benchmark": ((bench / "cases.csv").read_text(encoding="utf-8").splitlines()[0]
                          .lstrip("# ").split(" —")[0])}
    out = results / f"{a.label}.jsonl"
    with out.open("w", encoding="utf-8") as f:
        f.write(json.dumps({"meta": meta}) + "\n")
        for c in cases:
            f.write(json.dumps({"case_id": c["case_id"], "answer": answers.get(c["sha1_git"])}) + "\n")
    missing = sum(1 for c in cases if c["sha1_git"] not in answers)
    print(f"{a.label}: {len(cases) - missing}/{len(cases)} answered by synid {meta['version']} "
          f"({meta['commit'] or 'commit unknown'}), strategies {strategies} → {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
